#SPDX-License-Identifier: MIT-0
---
# defaults file for Jenkins
InstallJava: true
JavaVersion: 21
# JavaFlavor
# Can be
# Temurin
# OS
JavaFlavor: Temurin

UpdateAll: true

MandatoryPackages:
  - which
  - fontconfig
  - gpg