#SPDX-License-Identifier: MIT-0
---
# defaults file for Jenkins
InstallJava: true
JavaVersion: 21
# JavaFlavor
# Can be
# Temurin
# OS
JavaFlavor: Temurin
JavaOptionsCommon: 'JAVA_OPTS=-Djava.awt.headless=true -Djava.net.preferIPv4Stack=true'
JavaOptions:
  - '-Djava.io.tmpdir=Europe/Paris'
  - '-Dorg.apache.commons.jelly.tags.fmt.timeZone=/var/cache/jenkins/tmp'

JenkinsOptionsCommon: 'JENKINS_OPTS=--pluginroot=/var/cache/jenkins/plugins'

UpdateAll: true

MandatoryPackages:
  - which
  - fontconfig
  - gpg