#SPDX-License-Identifier: MIT-0
---
# defaults file for Jenkins
InstallJava: true
JavaVersion: 21
# JavaFlavor
# Can be
# Temurin
# OS
JavaFlavor: Temurin
JavaOptions:
  Prefix: 'JAVA_OPTS='
  Common: -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true
  TimeZone: 'Europe/Paris'
  TmpDir: '/var/cache/jenkins/tmp'

JenkinsOptions:
  Prefix: 'JENKINS_OPTS='
  PluginsDir: '/var/cache/jenkins/plugins'

UpdateAll: true

MandatoryPackages:
  - which
  - fontconfig
  - gpg