#SPDX-License-Identifier: MIT-0
---
# defaults file for Jenkins
InstallJava: true
JavaVersion: 21
# JavaFlavor
# Can be
# Temurin
# OS
JavaTZ: 'Europe/Paris'
Java_TmpDir: '/var/cache/jenkins/tmp'
JavaFlavor: Temurin
JenkinsUser: 'jenkins'
JavaOptionsCommon: 'JAVA_OPTS=-Djava.awt.headless=true -Djava.net.preferIPv4Stack=true'
JavaOptions:
  - '-Djava.io.tmpdir=/var/cache/jenkins/tmp'
  - '-Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Paris'

Jenkins_PluginDir: '/var/cache/jenkins/plugins'
JenkinsOptionsCommon: 'JENKINS_OPTS=--pluginroot=/var/cache/jenkins/plugins'
JenkinsDirectories:
  - '/var/cache/jenkins/plugins'
  - '/var/cache/jenkins/tmp'

UpdateAll: true

MandatoryPackages:
  - which
  - fontconfig
  - gpg
  - less
  - git