#SPDX-License-Identifier: MIT-0
---
# defaults file for Jenkins
InstallJava: true
JavaVersion: 21
JavaPackages:
  - "java-{{ JavaVersion }}-openjdk"
  - "java-{{ JavaVersion }}-openjdk-devel"

UpdateAll: true

MandatoryPackages:
  - which