#SPDX-License-Identifier: MIT-0
---
# tasks file for Jenkins
- name: Install mandatory packages
  ansible.builtin.package:
    name: "{{ MandatoryPackages }}"
    state: present

- name: Call update all task file
  ansible.builtin.include_tasks: UpdateAll.yaml
  when: UpdateAll | bool

- name: Call Install Java task file
  ansible.builtin.include_tasks: InstallJava.yaml
  when:
    - InstallJava | bool
    - JavaVersion is defined

- name: Actually install Jenkins
  ansible.builtin.include_tasks: InstallJenkins.yaml
...