---
JavaPackages:
  - "temurin-{{ JavaVersion }}-jdk"
ToBeRemovedJavaPachages:
  - java-11-openjdk
  - java-11-openjdk-devel
  - java-17-openjdk
  - java-17-openjdk-devel
  - java-21-openjdk
  - java-21-openjdk-devel
...