#SPDX-License-Identifier: MIT-0
---
# tasks file for Jenkins
- name: Update all
  ansible.builtin.include_tasks: UpdateAll.yaml
  when: UpdateAll | bool

- name: Install Java
  ansible.builtin.include_tasks: InstallJava.yaml
  when:
    - InstallJava | bool
    - JavaVersion is defined

...